# Exception Handling
---
## Exception handling
> Exception(예외처리)이란? 오류가 발생했을 시, 에러 메시지 대신에 프로그래머가 원하는 코드의 실행을 유도하는 작업이다.  

### Some common exceptions
- Attribute Error
```python
(2, 3, 1).sort() # sort 함수를 사용할 수 없는 tuple 이라서 Error가 난다.
print(x.endswith(3)) # endswith은 string method이다. int에 대해서는 Error이 난다.
```
- File Not Found Error : 없는 파일을 open하려고 했을 시 발생한다.
- Import Error : 없는 Module을 import 시 발생한다.
- Index Error : index의 out of range 발생 시 발생한다.
- Key Error : Dictionary에서 없는 key를 참조 시 발생한다.
- Name Error : 정의되지 않은 Variable 이름을 참조 시 발생한다.
- Type Error : 없는 type이나 잘못된 type 사용 시 발생한다.
- Value Error
```python
x = int('a') # 이렇게 말도 안되는 값에 대해 method를 실행 시 발생한다.
```
- Zero Division : 0으로 나누면 Runtime error이 발생한다.

### Try Statement
```python
try:
  numDependents = int(input("Enter number of dependents : "))
except ValueError: # 이제 값에 int가 아닌 잘못된 Value Error 이 발생했을 시, 이 Code를 실행하게 된다.
  print("\nYou did not respond with an integer value.")
  print("We will asssume your answer is zero.")
  numDependents = 0
taxCredit = 1000 * numDependents
print("Tax Credit : ", taxCredit)
```

```python
try:
  fileName = input("Enter the name of file : ")
  infile = open(fileName, 'r')
  num = float(infile.readline())
  print(1/num)
except FileNotFoundError as exc1: # 이미 내장되어있는 FileNotFoundError에 대한 출력 문장을 exc1로 만든다.
  print(exc1)
except TypeError as exc2: # 이미 내장되어있는 TypeError에 대한 출력 문장을 exc2로 만든다.
  print(exc2)
```

### Else and Finally Statement
```python
if foundFlag:
  try:
    for line in infile:
      count += 1
      total += float(line)
    print("Average : ", total / count)
  except ValueError:
    print("Line", count, "could not be converted to a float")
    if count > 1:
      print("Average so far : ", total / (count - 1))
      print("Total so far : ", total)
    else:
      print("No average can be calculated.")
  except ZeroDivisionError:
    print("File was empty.")
  else: # try에 대해서 Exception 발생 없이 여기까지 내려오면 결과를 출력한다.
    print("Total : ", total)
  finally: # exception이 발생하던, 무사히 else까지 도착하던간에 finally 내의 Code는 무조건 실행된다.
    infile.close()
```
- 여기서 알 수 있는 점은, Try문 하나에는 else문을 무조건 하나만 쓸 수 있다.
- Try와 Exception이 발생했건 안했건 Finally는 무조건 실행된다.
